easycoin/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('feedback.urls', namespace='feedback')),
    path('acl/admin/', admin.site.urls),
    path('login/', include('login.urls', namespace='login')),
    path('relatorio/', include('relatorio.urls', namespace='relatorio')),
    path('recargacoin/', include('recargacoin.urls', namespace='recarga')),
]

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'
urlpatterns = [
    path('', views.get_feedback, name='get_feedback'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
     path('', views.get_login, name='get_login'),
     path('auth_logout', views.auth_logout, name='auth_logout')
]

recargacoin/urls.py
from django.urls import path
from . import views

app_name = 'recargacoin'
urlpatterns = [
    path('', views.run, name='run'),
]

relatorio/urls.py
from django.urls import path
from . import views

app_name = 'relatorio'
urlpatterns = [
    path('', views.get_relatorio, name='get_relatorio'),
]

feedback/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


# Create your models here.
class Carteira(models.Model):
    pessoa = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    qtd_coin = models.IntegerField(default=0)
    qtd_coin_recebido = models.IntegerField(default=0)

    def __str__(self):
        return self.pessoa.first_name


class Feedback(models.Model):
    remetente = models.ForeignKey(
        Carteira, related_name='feedback_remetente', on_delete=models.CASCADE)
    destino = models.ForeignKey(Carteira, related_name='feedback_destino',
                                on_delete=models.CASCADE, verbose_name="Destinatário :")
    msg = models.TextField(max_length=255, verbose_name="Mensagem :")
    qtd_coin = models.PositiveIntegerField(validators=[MinValueValidator(1)],
        default=0, verbose_name="Quantidade easyCoin")
    data_pub = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.destino.pessoa.first_name

feedback/forms.py
from django import forms
from django.forms import ModelForm
from feedback.models import Feedback, Carteira

class FeedbackForm(ModelForm):

    class Meta:
        model = Feedback
        fields = ['destino', 'msg', 'qtd_coin']

    def save(self, commit=True):
        self.feedback = super(FeedbackForm, self).save(commit=False)
        destino = self.feedback.destino
        destino.qtd_coin_recebido =  destino.qtd_coin_recebido + self.feedback.qtd_coin
        destino.save()
        remet = Carteira.objects.get(pessoa=self.remetente)
        self.feedback.remetente = remet
        remet.qtd_coin = remet.qtd_coin - self.feedback.qtd_coin
        remet.save()
        if commit:
            self.feedback.save()
        return self.feedback

    def __init__(self, *args, **kwargs):
        self.remetente = kwargs.pop('remetente', None)
        if 'remetente' in kwargs:
            del kwargs['remetente']
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.fields['destino'].queryset = Carteira.objects.exclude(pessoa=self.remetente).order_by('id')

    def clean_qtd_coin(self):
        self.remetente_val = Carteira.objects.filter(pessoa=self.remetente).first().qtd_coin
        if self.cleaned_data['qtd_coin'] > self.remetente_val:
            raise forms.ValidationError("Quantidade insuficiente de Coin!")
        return self.cleaned_data['qtd_coin']

feedback/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import FeedbackForm
from feedback.models import Feedback, Carteira


# Create your views here.
@login_required
def get_feedback(request):
    if request.method == 'POST':
        envioFeedback = FeedbackForm(request.POST, remetente=request.user)
        if envioFeedback.is_valid():
            cd = envioFeedback.save()
            return HttpResponseRedirect('/')

    else:
        envioFeedback = FeedbackForm(remetente=request.user)

    dados = Carteira.objects.get(pessoa=request.user)
    feedForm = Feedback.objects.all().order_by('-data_pub')[:10]
    context_feed = {
        'form': envioFeedback,
        'feeds': feedForm,
        'dados': dados,
    }
    return render(request, 'feedback/index.html', context_feed)

feedback/templates/feedback/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>Feedback EasyCoin</title>
</head>
{% load i18n %}
<body>
<!--Menu-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">easyCoin</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Inicio<span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'relatorio:get_relatorio' %}">Relatorio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="acl/admin/">Gerenciamento</a>
      </li>
      <li class="nav-item">
      	<button type="button" id="modalopen" class="btn btn-primary" data-toggle="modal" data-target="#modalRecarga">Recarga Coin</button>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login:auth_logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>
<!-- Modal -->
<div class="modal fade" id="modalRecarga" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="modalRecarga">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="modalRecarga">Recarga Coin</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>Deseja realizar a recarga de todos os usuários?</p>
			</div>
			<div class="modal-footer">
				<a href="{% url 'recarga:run' %}" type="button" class="btn btn-primary">Sim</a>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Nao</button>
			</div>
		</div>
	</div>
</div>

<!--Coluna-->
<div class="container">
  <div class="row">
    <div class="col">
      {% block welcome %}
        {% trans 'Bem-vindo(a),' %}
        <strong>{% firstof user.first_name %} {% firstof user.last_name %}</strong>.
      {% endblock %}
      <br></br>
      <form method="post" class="form-group">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Submit" class="btn btn-primary">
      </form>
      <br/>
      <div>
        <strong>Meus Dados:</strong> {% firstof user.first_name %} {% firstof user.last_name %}</br>
        <strong>Quantidade easyCoin:</strong> {{ dados.qtd_coin }}</br>
        <strong>Qtd easyCoin Recebido:</strong> {{dados.qtd_coin_recebido }}
      </div>
    </div>
    <div class="col">
      <h1> Feed </h1>
      <!-- Card -->
      <div style="height: 500px; overflow-y: scroll;">
      {% for feed in feeds %}
        <div class="card">
          <div class="card-header">
            De: {{ feed.remetente }}
          </div>
          <div class="card-body">
            <h5 class="card-title">
             Para: {{ feed.destino }}, Qtd Coin Recebido: {{ feed.qtd_coin }}
            </h5>
            <p class="card-text" style="word-break: break-word;">
              {{ feed.msg }}
            </p>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
 </div>


</body>
</html>